;; Writes src/main/clojure/cljs/externs/default.edn, Closure's default
;; (browser) externs as cljs.externs/externs-map parses them, without docs and
;; source locations. cljs.env reads it when a build has no :externs-sources,
;; so the compiler doesn't need the Closure Compiler to get the types of
;; JavaScript's standard and browser APIs. Run script/gen-default-externs
;; after updating com.google.javascript/closure-compiler.

(require '[cljs.externs :as externs]
         '[clojure.edn :as edn]
         '[clojure.java.io :as io]
         '[clojure.string :as string])

(def out "src/main/clojure/cljs/externs/default.edn")

(def dropped-meta
  [:doc :file :line :column :end-line :end-column])

(defn strip [externs]
  (into {}
    (map (fn [[k v]]
           [(vary-meta k #(not-empty (apply dissoc % dropped-meta))) (strip v)]))
    externs))

(declare emit)

(defn emit-entries [m sep]
  (string/join sep (map (fn [[k v]] (str (emit k) " " (emit v))) (sort-by key m))))

(defn emit
  "x as EDN, with the metadata of symbols and map entries sorted by key, so the
  output doesn't depend on hash order."
  [x]
  (cond
    (map? x)    (str "{" (emit-entries x ", ") "}")
    (vector? x) (str "[" (string/join " " (map emit x)) "]")
    (seq? x)    (str "(" (string/join " " (map emit x)) ")")
    (symbol? x) (str (when-let [m (meta x)] (str "^{" (emit-entries m ", ") "} ")) x)
    :else       (pr-str x)))

(defn with-meta-tree
  "x with the metadata of the symbols in it as data, to compare metadata too."
  [x]
  (cond
    (map? x)    (into {} (map (fn [[k v]] [(with-meta-tree k) (with-meta-tree v)])) x)
    (coll? x)   (map with-meta-tree x)
    (symbol? x) [x (with-meta-tree (meta x))]
    :else       x))

(let [version  (second (re-find #"(?m)^version=(.+)$"
                                (slurp (io/resource "META-INF/maven/com.google.javascript/closure-compiler/pom.properties"))))
      externs  (strip (externs/externs-map))
      edn      (str ";; Closure's default externs, as cljs.externs/externs-map parses them, without\n"
                    ";; docs and source locations. Generated by script/gen-default-externs from\n"
                    ";; com.google.javascript/closure-compiler " version ", don't edit.\n"
                    "{" (emit-entries externs "\n ") "}\n")]
  (when-not (= (with-meta-tree externs) (with-meta-tree (edn/read-string edn)))
    (throw (ex-info "The generated EDN doesn't read back as the externs map" {})))
  (io/make-parents out)
  (spit out edn)
  (println "Wrote" out))
